// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: rpg/v1/api.proto

package rpgv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ChandonJarrett/authoritative-multiplayer-rpg-backend/internal/protocol/rpg/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SystemServiceName is the fully-qualified name of the SystemService service.
	SystemServiceName = "rpg.v1.SystemService"
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "rpg.v1.AuthService"
	// CharacterServiceName is the fully-qualified name of the CharacterService service.
	CharacterServiceName = "rpg.v1.CharacterService"
	// GameServiceName is the fully-qualified name of the GameService service.
	GameServiceName = "rpg.v1.GameService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SystemServicePingProcedure is the fully-qualified name of the SystemService's Ping RPC.
	SystemServicePingProcedure = "/rpg.v1.SystemService/Ping"
	// AuthServiceRegisterProcedure is the fully-qualified name of the AuthService's Register RPC.
	AuthServiceRegisterProcedure = "/rpg.v1.AuthService/Register"
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/rpg.v1.AuthService/Login"
	// CharacterServiceCreateCharacterProcedure is the fully-qualified name of the CharacterService's
	// CreateCharacter RPC.
	CharacterServiceCreateCharacterProcedure = "/rpg.v1.CharacterService/CreateCharacter"
	// CharacterServiceListCharactersProcedure is the fully-qualified name of the CharacterService's
	// ListCharacters RPC.
	CharacterServiceListCharactersProcedure = "/rpg.v1.CharacterService/ListCharacters"
	// GameServiceIssueJoinTokenProcedure is the fully-qualified name of the GameService's
	// IssueJoinToken RPC.
	GameServiceIssueJoinTokenProcedure = "/rpg.v1.GameService/IssueJoinToken"
)

// SystemServiceClient is a client for the rpg.v1.SystemService service.
type SystemServiceClient interface {
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
}

// NewSystemServiceClient constructs a client for the rpg.v1.SystemService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSystemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SystemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	systemServiceMethods := v1.File_rpg_v1_api_proto.Services().ByName("SystemService").Methods()
	return &systemServiceClient{
		ping: connect.NewClient[v1.PingRequest, v1.PingResponse](
			httpClient,
			baseURL+SystemServicePingProcedure,
			connect.WithSchema(systemServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
	}
}

// systemServiceClient implements SystemServiceClient.
type systemServiceClient struct {
	ping *connect.Client[v1.PingRequest, v1.PingResponse]
}

// Ping calls rpg.v1.SystemService.Ping.
func (c *systemServiceClient) Ping(ctx context.Context, req *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// SystemServiceHandler is an implementation of the rpg.v1.SystemService service.
type SystemServiceHandler interface {
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
}

// NewSystemServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSystemServiceHandler(svc SystemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	systemServiceMethods := v1.File_rpg_v1_api_proto.Services().ByName("SystemService").Methods()
	systemServicePingHandler := connect.NewUnaryHandler(
		SystemServicePingProcedure,
		svc.Ping,
		connect.WithSchema(systemServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpg.v1.SystemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SystemServicePingProcedure:
			systemServicePingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSystemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSystemServiceHandler struct{}

func (UnimplementedSystemServiceHandler) Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpg.v1.SystemService.Ping is not implemented"))
}

// AuthServiceClient is a client for the rpg.v1.AuthService service.
type AuthServiceClient interface {
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
}

// NewAuthServiceClient constructs a client for the rpg.v1.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_rpg_v1_api_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		register: connect.NewClient[v1.RegisterRequest, v1.RegisterResponse](
			httpClient,
			baseURL+AuthServiceRegisterProcedure,
			connect.WithSchema(authServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	register *connect.Client[v1.RegisterRequest, v1.RegisterResponse]
	login    *connect.Client[v1.LoginRequest, v1.LoginResponse]
}

// Register calls rpg.v1.AuthService.Register.
func (c *authServiceClient) Register(ctx context.Context, req *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Login calls rpg.v1.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the rpg.v1.AuthService service.
type AuthServiceHandler interface {
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_rpg_v1_api_proto.Services().ByName("AuthService").Methods()
	authServiceRegisterHandler := connect.NewUnaryHandler(
		AuthServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(authServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpg.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceRegisterProcedure:
			authServiceRegisterHandler.ServeHTTP(w, r)
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpg.v1.AuthService.Register is not implemented"))
}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpg.v1.AuthService.Login is not implemented"))
}

// CharacterServiceClient is a client for the rpg.v1.CharacterService service.
type CharacterServiceClient interface {
	CreateCharacter(context.Context, *connect.Request[v1.CreateCharacterRequest]) (*connect.Response[v1.CreateCharacterResponse], error)
	ListCharacters(context.Context, *connect.Request[v1.ListCharactersRequest]) (*connect.Response[v1.ListCharactersResponse], error)
}

// NewCharacterServiceClient constructs a client for the rpg.v1.CharacterService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCharacterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CharacterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	characterServiceMethods := v1.File_rpg_v1_api_proto.Services().ByName("CharacterService").Methods()
	return &characterServiceClient{
		createCharacter: connect.NewClient[v1.CreateCharacterRequest, v1.CreateCharacterResponse](
			httpClient,
			baseURL+CharacterServiceCreateCharacterProcedure,
			connect.WithSchema(characterServiceMethods.ByName("CreateCharacter")),
			connect.WithClientOptions(opts...),
		),
		listCharacters: connect.NewClient[v1.ListCharactersRequest, v1.ListCharactersResponse](
			httpClient,
			baseURL+CharacterServiceListCharactersProcedure,
			connect.WithSchema(characterServiceMethods.ByName("ListCharacters")),
			connect.WithClientOptions(opts...),
		),
	}
}

// characterServiceClient implements CharacterServiceClient.
type characterServiceClient struct {
	createCharacter *connect.Client[v1.CreateCharacterRequest, v1.CreateCharacterResponse]
	listCharacters  *connect.Client[v1.ListCharactersRequest, v1.ListCharactersResponse]
}

// CreateCharacter calls rpg.v1.CharacterService.CreateCharacter.
func (c *characterServiceClient) CreateCharacter(ctx context.Context, req *connect.Request[v1.CreateCharacterRequest]) (*connect.Response[v1.CreateCharacterResponse], error) {
	return c.createCharacter.CallUnary(ctx, req)
}

// ListCharacters calls rpg.v1.CharacterService.ListCharacters.
func (c *characterServiceClient) ListCharacters(ctx context.Context, req *connect.Request[v1.ListCharactersRequest]) (*connect.Response[v1.ListCharactersResponse], error) {
	return c.listCharacters.CallUnary(ctx, req)
}

// CharacterServiceHandler is an implementation of the rpg.v1.CharacterService service.
type CharacterServiceHandler interface {
	CreateCharacter(context.Context, *connect.Request[v1.CreateCharacterRequest]) (*connect.Response[v1.CreateCharacterResponse], error)
	ListCharacters(context.Context, *connect.Request[v1.ListCharactersRequest]) (*connect.Response[v1.ListCharactersResponse], error)
}

// NewCharacterServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCharacterServiceHandler(svc CharacterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	characterServiceMethods := v1.File_rpg_v1_api_proto.Services().ByName("CharacterService").Methods()
	characterServiceCreateCharacterHandler := connect.NewUnaryHandler(
		CharacterServiceCreateCharacterProcedure,
		svc.CreateCharacter,
		connect.WithSchema(characterServiceMethods.ByName("CreateCharacter")),
		connect.WithHandlerOptions(opts...),
	)
	characterServiceListCharactersHandler := connect.NewUnaryHandler(
		CharacterServiceListCharactersProcedure,
		svc.ListCharacters,
		connect.WithSchema(characterServiceMethods.ByName("ListCharacters")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpg.v1.CharacterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CharacterServiceCreateCharacterProcedure:
			characterServiceCreateCharacterHandler.ServeHTTP(w, r)
		case CharacterServiceListCharactersProcedure:
			characterServiceListCharactersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCharacterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCharacterServiceHandler struct{}

func (UnimplementedCharacterServiceHandler) CreateCharacter(context.Context, *connect.Request[v1.CreateCharacterRequest]) (*connect.Response[v1.CreateCharacterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpg.v1.CharacterService.CreateCharacter is not implemented"))
}

func (UnimplementedCharacterServiceHandler) ListCharacters(context.Context, *connect.Request[v1.ListCharactersRequest]) (*connect.Response[v1.ListCharactersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpg.v1.CharacterService.ListCharacters is not implemented"))
}

// GameServiceClient is a client for the rpg.v1.GameService service.
type GameServiceClient interface {
	IssueJoinToken(context.Context, *connect.Request[v1.IssueJoinTokenRequest]) (*connect.Response[v1.IssueJoinTokenResponse], error)
}

// NewGameServiceClient constructs a client for the rpg.v1.GameService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGameServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GameServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gameServiceMethods := v1.File_rpg_v1_api_proto.Services().ByName("GameService").Methods()
	return &gameServiceClient{
		issueJoinToken: connect.NewClient[v1.IssueJoinTokenRequest, v1.IssueJoinTokenResponse](
			httpClient,
			baseURL+GameServiceIssueJoinTokenProcedure,
			connect.WithSchema(gameServiceMethods.ByName("IssueJoinToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gameServiceClient implements GameServiceClient.
type gameServiceClient struct {
	issueJoinToken *connect.Client[v1.IssueJoinTokenRequest, v1.IssueJoinTokenResponse]
}

// IssueJoinToken calls rpg.v1.GameService.IssueJoinToken.
func (c *gameServiceClient) IssueJoinToken(ctx context.Context, req *connect.Request[v1.IssueJoinTokenRequest]) (*connect.Response[v1.IssueJoinTokenResponse], error) {
	return c.issueJoinToken.CallUnary(ctx, req)
}

// GameServiceHandler is an implementation of the rpg.v1.GameService service.
type GameServiceHandler interface {
	IssueJoinToken(context.Context, *connect.Request[v1.IssueJoinTokenRequest]) (*connect.Response[v1.IssueJoinTokenResponse], error)
}

// NewGameServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGameServiceHandler(svc GameServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gameServiceMethods := v1.File_rpg_v1_api_proto.Services().ByName("GameService").Methods()
	gameServiceIssueJoinTokenHandler := connect.NewUnaryHandler(
		GameServiceIssueJoinTokenProcedure,
		svc.IssueJoinToken,
		connect.WithSchema(gameServiceMethods.ByName("IssueJoinToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpg.v1.GameService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GameServiceIssueJoinTokenProcedure:
			gameServiceIssueJoinTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGameServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGameServiceHandler struct{}

func (UnimplementedGameServiceHandler) IssueJoinToken(context.Context, *connect.Request[v1.IssueJoinTokenRequest]) (*connect.Response[v1.IssueJoinTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpg.v1.GameService.IssueJoinToken is not implemented"))
}
