// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rpg/v1/common.proto

package rpgv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vec3 represents a point or vector in 3D space.
type Vec3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec3) Reset() {
	*x = Vec3{}
	mi := &file_rpg_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec3) ProtoMessage() {}

func (x *Vec3) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec3.ProtoReflect.Descriptor instead.
func (*Vec3) Descriptor() ([]byte, []int) {
	return file_rpg_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Vec3) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec3) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vec3) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_rpg_v1_common_proto protoreflect.FileDescriptor

const file_rpg_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x13rpg/v1/common.proto\x12\x06rpg.v1\"0\n" +
	"\x04Vec3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01zB`Z^github.com/ChandonJarrett/authoritative-multiplayer-rpg-backend/internal/protocol/rpg/v1;rpgv1b\x06proto3"

var (
	file_rpg_v1_common_proto_rawDescOnce sync.Once
	file_rpg_v1_common_proto_rawDescData []byte
)

func file_rpg_v1_common_proto_rawDescGZIP() []byte {
	file_rpg_v1_common_proto_rawDescOnce.Do(func() {
		file_rpg_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpg_v1_common_proto_rawDesc), len(file_rpg_v1_common_proto_rawDesc)))
	})
	return file_rpg_v1_common_proto_rawDescData
}

var file_rpg_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rpg_v1_common_proto_goTypes = []any{
	(*Vec3)(nil), // 0: rpg.v1.Vec3
}
var file_rpg_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpg_v1_common_proto_init() }
func file_rpg_v1_common_proto_init() {
	if File_rpg_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpg_v1_common_proto_rawDesc), len(file_rpg_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpg_v1_common_proto_goTypes,
		DependencyIndexes: file_rpg_v1_common_proto_depIdxs,
		MessageInfos:      file_rpg_v1_common_proto_msgTypes,
	}.Build()
	File_rpg_v1_common_proto = out.File
	file_rpg_v1_common_proto_goTypes = nil
	file_rpg_v1_common_proto_depIdxs = nil
}
