// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rpg/v1/game.proto

package rpgv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JoinRequest is the first packet a client sends after connecting via ENet. The join_token is issued by the API server (IssueJoinToken RPC) and is short-lived and single-use.
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinToken     string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	CharacterId   string                 `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_rpg_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_rpg_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *JoinRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

// JoinResponse is sent by the game server in response to JoinRequest.
type JoinResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// reason is populated on failure and empty on success.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_rpg_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpg_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_rpg_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *JoinResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_rpg_v1_game_proto protoreflect.FileDescriptor

const file_rpg_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x11rpg/v1/game.proto\x12\x06rpg.v1\"O\n" +
	"\vJoinRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\tR\vcharacterId\"6\n" +
	"\fJoinResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reasonB`Z^github.com/ChandonJarrett/authoritative-multiplayer-rpg-backend/internal/protocol/rpg/v1;rpgv1b\x06proto3"

var (
	file_rpg_v1_game_proto_rawDescOnce sync.Once
	file_rpg_v1_game_proto_rawDescData []byte
)

func file_rpg_v1_game_proto_rawDescGZIP() []byte {
	file_rpg_v1_game_proto_rawDescOnce.Do(func() {
		file_rpg_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpg_v1_game_proto_rawDesc), len(file_rpg_v1_game_proto_rawDesc)))
	})
	return file_rpg_v1_game_proto_rawDescData
}

var file_rpg_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpg_v1_game_proto_goTypes = []any{
	(*JoinRequest)(nil),  // 0: rpg.v1.JoinRequest
	(*JoinResponse)(nil), // 1: rpg.v1.JoinResponse
}
var file_rpg_v1_game_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpg_v1_game_proto_init() }
func file_rpg_v1_game_proto_init() {
	if File_rpg_v1_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpg_v1_game_proto_rawDesc), len(file_rpg_v1_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpg_v1_game_proto_goTypes,
		DependencyIndexes: file_rpg_v1_game_proto_depIdxs,
		MessageInfos:      file_rpg_v1_game_proto_msgTypes,
	}.Build()
	File_rpg_v1_game_proto = out.File
	file_rpg_v1_game_proto_goTypes = nil
	file_rpg_v1_game_proto_depIdxs = nil
}
